spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          destination: demo
          contentType: application/json
        greetings-out:
          destination: demo
          contentType: application/json
server:
  port: 8081

